### ISSUE TITLE
PRCA scraping bug

### ISSUE THREAD

**Issue by wrrrrn** [spudmind/spud#82]
(uti-env)root@undetheinfluence:~/uti# python task_runner.py --scrape prca -v
Scraping PRCA
... agency_2014-09_2014-11.pdf
parsing: /root/uti/scrapers/prca/store/agency_2014-09_2014-11.pdf
Traceback (most recent call last):
  File "task_runner.py", line 76, in <module>
    exec_scraper[scraper].scrape()
  File "/root/uti/scrapers/prca/scrape_prca.py", line 199, in scrape
    ScrapePRCA().run()
  File "/root/uti/scrapers/prca/scrape_prca.py", line 195, in run
    self.parse_file(meta)
  File "/root/uti/scrapers/prca/scrape_prca.py", line 174, in parse_file
    blocks = self.scrape_blocks_from_pdf(full_path)
  File "/root/uti/scrapers/prca/scrape_prca.py", line 56, in scrape_blocks_from_pdf
    pdf = pdftoxml.from_file(filename)
  File "/root/uti/utils/pdftoxml.py", line 172, in from_file
    return PDFtoXML(filename)
  File "/root/uti/utils/pdftoxml.py", line 20, in __init__
    self._xml = lxml.etree.fromstring(xml_string)
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106307)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105098)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99780)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94969)
lxml.etree.XMLSyntaxError: None

**Comment by andylolz** [comment]
This one is fixed now, right?

In case we forget – the problem here was pdftohtml was missing.

**Comment by wrrrrn** [comment]
It is yes. I'll check double check that I've added it to the install
instructions
